### ISSUE TITLE
Timeout during yaml rest test

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/opensearch-ubi#139]
The `Events` yaml rest test is timing out while waiting for the cluster to be healthy.

```
        java.lang.AssertionError: expected [2xx] status code but api [cluster.health] returned [408 Request Timeout] [{"cluster_name":"yamlRestTest","status":"red","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}]
            at org.junit.Assert.fail(Assert.java:89)
            at org.opensearch.test.rest.yaml.section.DoSection.execute(DoSection.java:328)
            at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:449)
            ... 41 more
```

This is causing a failing [build](https://github.com/o19s/opensearch-ubi/actions/runs/8422883564/job/23063212253).

**Comment by jzonthemtn** [comment]
There appears to be two issues here:

* The `events-mapping.json` file is not valid JSON.
* Once made to be valid JSON, the mapping itself is invalid:

```
org.opensearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: Mapping definition for [position] has unsupported parameters:  [object : {properties={transaction_id={ignore_above=100, type=keyword}, object_type={ignore_above=100, type=keyword}, to_user_id={ignore_above=100, type=keyword}, object_detail={type=object}, description={type=text, fields={keyword={ignore_above=256, type=keyword}}}, object_id={ignore_above=256, type=keyword}}}]
```

This is what causes the timeout waiting for the cluster to startup in the yaml test.

**Comment by jzonthemtn** [comment]
#141 is to add JSON syntax checking to the build to be able to find the problem earlier. Letting it fail in the REST test requires working backward to find the actual problem. Typos/problems in the mapping files could be found faster if checked separately in the build.
